### ISSUE TITLE
Other real-time tracking of R_t

### ISSUE THREAD

**Issue by smbartell** [k-sys/covid-19#13]
It's really great to see someone tackling this for the US, but there is another project tracking R_t in real time using Bayesian updating, in Europe:  https://mrc-ide.github.io/covid19estimates/#/   Their model is more structured, but that has pros and cons.  I really like that your model is less constrained with regard to how R_t changes over time, as behavior can change rapidly as people become more cautious, start wearing masks, etc.  But you might get some other ideas about modeling from their approach.

**Comment by k-sys** [comment]
Thank you!
