### ISSUE TITLE
Puerto Rico specifically filtered out?

### ISSUE THREAD

**Issue by Vivtek** [k-sys/covid-19#18]
I spent some time looking at the data to see why Puerto Rico was not being included in the final results despite being in the underlying data, only finally to realize that we're not in there because you'd *specifically removed us*.

Why?

**Comment by webteckie** [comment]
Yes, totally agree! Please consider removing that filter as it is useful for us as well!

**Comment by k-sys** [comment]
The title and scope of the notebook was US states (arguably DC is not a state, though hard to exclude). Another technical reason was that case counts were so low in VI/AS/etc that they didn't work with the algorithm so I made the decision to just focus on the states. No offense meant, just a scope decision (could very well have run this for countries). If you'd like to run this for PR or any other territory it's very easy to fork and/or import new data locally.
