### ISSUE TITLE
Overshoot on WA, maybe could apply signal processing techniques?

### ISSUE THREAD

**Issue by femto113** [k-sys/covid-19#19]
The WA chart zooming past 1 and bouncing off 0 reminds me very much of the sort of overshoot you get in signal processing (where you go past the target level), which is typically followed by ringing (where you oscillate around the target level for a while before settling down).  I'm not well-versed enough in the science to see exactly where/how this might be applied in your model, but the standard fix is to attenuate any of the high frequency inputs (e.g. with a low pass filter).  Perhaps you can solicit input from someone with relevant experience, I think it could help to make these more accurate.  It seems particularly relevant if trying to make these usable for policy, since you really don't want knee jerk reactions to artifacts that aren't really part of the data.

**Comment by BryantD** [comment]
I noticed this too. Washington’s data was pretty bad from 4/7 to 4/15 — several days reporting either 0 new cases or 0 deaths. I’m not sure how you’d address this but another alternative might be a wider confidence band. The source data does rate data quality for each state.

**Comment by k-sys** [comment]
Thank you for sending. I'll have to think about using signal processing... right now i use a simple gaussian filter for new cases. There's like a better solution but I'm not sure it'll make a huge difference in the outcome. Thanks for the input! (agree WA looks bad in those dates)

Kevin

**Comment by femto113** [comment]
Here's a a compounding issue, which is likely present everywhere but is clearer in WA because of multiple reporting sources.  covidtracking.com records new positives on the date they were reported, but this is generally not the date the tested individual got ill.  WA DOH has a report they call the "epidemiological curve" where positives are assigned to the date of onset of symptoms, which is likely much closer.  Chart below shows the difference, with covidtracking.com's `positiveIncrease` column as the blue line and WA DOH's epi curve as the orange bars.  You can see the curve is  both smoother and earlier, and I expect much closer to reality (though it does still show strong weekday/weekend artifacts).   This suggests to me that it would make sense to add a step where you distribute the reported cases each day backwards to the time they most likely became infectious.  In the absence of a specific reference model you could perhaps do that distribution in the way that minimizes the implied change in Rt.

![Screen Shot 2020-04-19 at 1 41 46 PM](https://user-images.githubusercontent.com/184827/79699378-22b69700-8244-11ea-9f27-40a16f80e480.png)

[wa-ctc-v-doh-ec.xlsx](https://github.com/k-sys/covid-19/files/4500233/wa-ctc-v-doh-ec.xlsx)

WA DOH data from https://www.doh.wa.gov/emergencies/coronavirus

**Comment by femto113** [comment]
Here's a simple stab at spreading reported cases backwards using Poisson distributions for how many days ago the case reported symptoms.  For the chart below each day's reported cases were distributed across the past 14 days with a mean of 5 days ago, then for each day summed all of the cases assumed to start on that day.  Reported cases are red dots, "actual" onsets are blue dots, summed up cases are in purple.  Not sure yet if this works any better than the rolling gaussian, and I think it implies that you can't actually calculate Rt for any time more recent than that assumed mean.

<img width="697" alt="Screen Shot 2020-04-20 at 11 56 57 AM" src="https://user-images.githubusercontent.com/184827/79789402-f7dd4900-82fe-11ea-91dd-681d070d4a8c.png">

**Comment by jstover79** [comment]
Possibly relelvant:

I just checked WA State's official data, which I imagine is edited/cleaned periodically. Their daily case counts are quite out of sync with the covid tracking project dataset. I just commented this on covidtracking's github too. From the covidtracking dataset, it is clear that WA has experienced an increase in spread consistent with your increased Rt calculation. (That's a good thing I suppose!) But the official WA data is now very different. 

Case counts: 
For 4/20 to 4/15:
WA State data (as of 5:15 pm pacific time)
12085, 12071, 12054,   11975, 11772,
COVID tracking data:
11790, 11802, 11445, 11152, 10783,

with discrepancies currently 200+, but previously 900+ (and back in march in the thousands).

Intuitively, this makes your Rt calculation out of sync with the "official" data. I'm not sure if similar issues exist with other state's datasets, but I imagine they do. I'm hoping that someone will pull together all these data sources and periodically update the historical data to reflect the official state data. From the official WA data, it looks like WA should probably still be in the "under control" category with a VERY low Rt.

Thank you so much for this work.

**Comment by k-sys** [comment]
So there are two issues here: (1) is overreaction to non-reporting or double-reporting days and (2) is the difference between reporting and onset. While fixing 2 slightly fixes (1) it is not the same issue. I need to fix both of them. Per Femto's suggestion, the right thing to do for onset is to effectively convolve the cases backwards to onset. You then have a problem of lack of data in the last N days, but it appears that you can solve that using some techniques that the epiforecast.io folks use.

On (1) I think something like a kalman filter is going to be useful but I want to make sure to find the right solution before changing methodology as this notebook powers rt.live as well. This is a priority for me in the next day or so

**Comment by femto113** [comment]
@k-sys your recent updates to the model look really solid, and seem to have "fixed" the WA problem so I think the original suggestion about signal processing can just be ignored.   (I wonder if it can help with the weekend/weekday reporting problem, but I think varying the backwards distribution by the day of week of the report can probably solve that even easier).
