### ISSUE TITLE
Stability in NY estimates

### ISSUE THREAD

**Issue by batson** [k-sys/covid-19#23]
I'm trying to get a handle on how to compare estimates from day to day. Here is the delta between yesterday's estimate for NYC and today's from the website [rt.live](rt.live).

**Yesterday**:
<img width="472" alt="Screen Shot 2020-04-18 at 6 26 29 PM" src="https://user-images.githubusercontent.com/1261162/79698803-395aef00-8240-11ea-80e3-18b5a8caeee2.png">

**Today**:
<img width="519" alt="Screen Shot 2020-04-19 at 1 14 12 PM" src="https://user-images.githubusercontent.com/1261162/79698808-3eb83980-8240-11ea-9f7a-c3f7c3270921.png">

My intuition is that the model is local (modulo the 9 day gaussian smoothing), and forward looking, so adding one day of data shouldn't change the error bars (eg around March 22), nor so dramatically shift the endpoint. A large change in the inferred sigma could cause the expansion of the error bars.

Was there a change in data source?

**Comment by richardeschloss** [comment]
I think the issue is that the data is for the whole state of NY, not just NYC.  I think looking into NYC, we'd see the Rt well above 1. I think it would be more useful if the Rt charts could drill down to cities. JHU data gives the cities in the column "Combined_Key"

**Comment by batson** [comment]
The city level data would also be interesting.

My concern here is less about the precise value of Rt in NY, and more about the changes in the model's predictions and error bars between consecutive days/runs. (This may indicate a change of data sources, model, or sensitivity of the whole predicted path to a final day of data.)

**Comment by k-sys** [comment]
Hi guys, actually this was a change in model - we (prematurely) switched to a new method and decided that wasn't right. Instead we decided to keep with the notebook math so that there's a 1:1 relationship.

Separately, the smoothing as it stands today overweights recent observations which is a known issue and I'll be working on a solution over the next day. Sorry for the confusion - you should see lots more stability going forward.

**Comment by batson** [comment]
Thanks for the clarification, @k-sys!
