### ISSUE TITLE
Likelihood Notation

### ISSUE THREAD

**Issue by syasini** [k-sys/covid-19#4]
Excellent analysis! 

The likelihood notation is a bit confusing. ℒ should indicate the "likelihood" of observing the data, given the model parameters, not the other way around. If I understand correctly, in this case, the observed data is k and the model parameter is R_t so the likelihood should be noted as ℒ (k | R_t). This is used correctly where the Poisson model is introduced, but not elsewhere.

**Comment by k-sys** [comment]
Will look into this.

**Comment by gilesvangruisen** [comment]
I noticed the same as @syasini. The implementation looks correct, but the notation in the text is slightly off:

> This is Bayes' Theorem as we'll use it
>
> <img src="https://render.githubusercontent.com/render/math?math=P(R_t|k)=\frac{P(R_t)\cdot\mathcal{L}(R_t|k)}{P(k)}">

----

 Bayes theorem states that:

<img src="https://render.githubusercontent.com/render/math?math=P(A|B)=\frac{P(A)\cdot\\P(B|A)}{P(B)}">

I.e. the numerator specifies the product of <img src="https://render.githubusercontent.com/render/math?math=P(A)"> and <img src="https://render.githubusercontent.com/render/math?math=P(B|A)">. 

In this case, we're looking at the probability of <img src="https://render.githubusercontent.com/render/math?math=R_t"> given <img src="https://render.githubusercontent.com/render/math?math=k"> so, I think the correct notation should be:

<img src="https://render.githubusercontent.com/render/math?math=P(R_t|k)=\frac{P(R_t)\cdot\mathcal{L}(k|R_t)}{P(k)}">
