### ISSUE TITLE
Translation From Confirmed Date to Onset Date May Not Be Correct

### ISSUE THREAD

**Issue by farr** [k-sys/covid-19#43]
I am worried about the translation from confirmed date backwards to onset date in the new `Realtime Rt MCMC.ipynb` notebook.  A few points that are worrisome first:

* If I try to translate the "Adjusted Onset" curve *forward* again to check against the "Confirmed" curve, they do not match (in fact, the forward-translated Adjusted Onset curve is *even smoother* and *flatter* than the Adjusted Onset curve---since will have been convolved *yet again* with a broad kernel).

* The broad distribution of confirmed dates given an onset date acts as a *smoothing* operation that "goes the wrong way."  Consider a single burst of onset at day 0 (a "delta function" in the onset): since there are a range of delays between each patient's onset and confirmation, the confirmation curve will be a copy of the delay distribution (scaled by the number of onsets in the burst).  (To be technical: the delay distribution is the Green's function for the onset -> confirmation process.). A sharp peak in onset smooths out into a broad range of confirmation dates.  So, if anything, the onset time series should be *sharper* or *less smooth* than the confirmation time series, but your curves go the opposite way.

I think you should be *de*convolving by the onset->confirmation delay distribution (which, in general, is a mathematically ill-posed problem, unless the distribution is of a special class).  To make it well-posed, you should be *inferring* the distribution of onsets conditional on the confirmation observations (by sampling over variables that are onset rates, which get convolved with your distribution of delays, and then matched to confirmation observations), subject to some prior (probably something smoothing like the Gaussian-increments prior you've employed for estimating Rt).

**Comment by pati610** [comment]
I'm checking your latest commit right now. It looks highly interesting. A huge thanks for including the conda environment, much appreciated!

**Comment by k-sys** [comment]
Hi Will - I need to read this more closely, but one test I did was this: take 100 cases on a single day and run it through the algo - it produces what you'd expect (eg cases distributed into the past a la the delay distribution). However, I *think* (need to think more) that translating it back is harder than what you're describing.  You should technically be able to assign each onset a probable report time, but by doing that you're going from report->onset->report and there's no way you can deterministically recover the original series (you'd get the effect you're seeing with convolving twice).

But just to step back here, I've been following the methods here:

https://epiforecasts.io/covid/methods.html

Those folks are far more versed in this than I am. If you believe I've interpreted their work incorrectly please let me know.

Kevin

**Comment by farr** [comment]
Hi Kevin,

Thanks for taking a look at this---I've had a close look at their methods document, and I guess I really take issue with that.  That is to say, I think you've implemented their method faithfully.  (And they *do* know a lot more epidemiology than I do, for sure.)

I don't think I expressed myself very clearly, but I think you've got the gist: my point is exactly that the translation report -> onset -> report is not indempotent, but *should* be.  Ideally, as you suggest, you should really run a generative model *forward*: that is, there should be a time series of parameters that give the infection numbers on each day, following the exponential growth identified with the time-varying Rt parameters.  Then you take those parameters and convolve with the infection -> onset delay distribution (mean ~5 days) to get an onset time series.  Then convolve *that* with the onset -> confirm delay distribution that you have fit.  Then match the resulting confirm timeseries to the observations.

I built such a model yesterday, but, as suspected, it *amplifies* the daily fluctuations in the observations of confirmed cases, so the infection time series gets *really jumpy*, and R_t is basically junk (fluctuates from +15 to -15 day-to-day).  You can smooth the crap out of the observations to get something reasonable, but that sorta defeats the purpose of the model anyway; and you *still* have to impose a very strong smoothness prior (i.e. force sigma to be very small) in order to get any confidence day-to-day, since the passage from infection -> onset -> confirm washes out day-to-day fluctuations in the infection series (i.e. these are unconstrained by the *data*, so you just get whatever prior you put in).

Final point: *if* everything is exponential (infection time series, delay time distributions, etc), then convolving an exponential with another exponential doesn't change the time-constant, just the normalization---so you could argue that the original model, where you fit Rt *of the confirmations of cases* will give a consistent Rt with the infection time series, just shifted by ~10 days or so.  

Given all that, I've left my code as-is, and estimate Rt from the (smoothed) confirmed time series, finding more-or-less consistent results to yours (but some variation in the details---for example, my NY series ![image](https://user-images.githubusercontent.com/90048/80268545-ee910b00-8675-11ea-8308-b11441e1694d.png) shows NY confidently below R_t = 1, while yours suggests that today it's a bit above 1 (by eye, the difference is all in the rise in the last few days in your model---as would be expected from the right-censoring correction).

I also moved to using the JHU data set---feel free to crib the code I used; I see a lot of by-hand corrections in your latest notebook, so maybe the JHU data is more reliable.

Finally, to step back, as you say: you're faithfully implementing the epiforecasts methods, and that's the right thing to do for a public-facing website like this (I'll get in touch with them with my objections, and maybe we can hash it out in the epi literature---but for now I agree that we need to trust the experts on this).

Given all this, I'm closing the issue.
