### ISSUE TITLE
Highest Density Interval

### ISSUE THREAD

**Issue by syasini** [k-sys/covid-19#5]
This is just a comment regarding the highest density interval. 

If the posterior was calculated using MCMC chains, the `pymc3.stats.hpd` function from the PyMC3 package could have been used. Although I don't think it'll work for the pmf directly, there might be a way to tweak it. 

Feel free to close this without a response.

**Comment by k-sys** [comment]
The posterior isn't calculated that way - it's actually multiplying the estimated distributions. You're right though that that would be a helpful function (I looked at the source before and came to the conclusion it wasn't a fit). Thank you
