### ISSUE TITLE
Adjusted onset not being used for sampling

### ISSUE THREAD

**Issue by perone** [k-sys/covid-19#51]
Great notebooks. I was reviewing the notebook because I'm planning to use for some modelling and I found that block of code:

```
def create_and_run_model(name, state):
    confirmed = state.positive.diff().dropna()
    onset = confirmed_to_onset(confirmed, p_delay)
    adjusted, cumulative_p_delay = adjust_onset_for_right_censorship(onset, p_delay)
    return MCMCModel(name, onset, cumulative_p_delay).run()
```
The `adjusted` series, which is the onset with the right censorship adjusted is being computed but it is not the one used on the `MCMCModel` later, is there a reason for this or is it a typo ?

**Comment by k-sys** [comment]
Correct. I'm so sorry for the lack of updates but we've been trying to productionize this code for the site. It's changed quite a bit but this version is still useful. The code is pretty messy though, I'm very sorry about that.

The model specifically takes onsets not expected actual cases... so the adjusted series is not useful (except for an interesting graph!)

Kevin

**Comment by perone** [comment]
Thanks for the quick answer @k-sys !
